name: GitHub api Actions

on:
  push:
    branches: [github-actions]
  pull_request:
    branches: [github-actions]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run lint
